import type {
  Cita,
  Profesional,
  KpiSemana,
  DistribucionVertical,
  TurnosDia,
  PerformanceProfesional,
  EmbudioHorario,
} from "./types";

export const PROFESIONALES: Profesional[] = [
  { id: "ayala", nombre: "Ayala Vázquez", especialidad: "Medicina del Dolor", vertical_default: "dolor", activo: true },
  { id: "saravia", nombre: "Saravia Toledo", especialidad: "Medicina del Dolor", vertical_default: "dolor", activo: true },
  { id: "garbelino", nombre: "Garbelino Moliné", especialidad: "Longevidad", vertical_default: "longevidad", activo: true },
  { id: "ficcadenti", nombre: "Ficcadenti", especialidad: "Longevidad / Sueroterapia", vertical_default: "longevidad", activo: true },
  { id: "rollan", nombre: "Rollán", especialidad: "Longevidad", vertical_default: "longevidad", activo: true },
  { id: "vanetta", nombre: "Vanetta", especialidad: "Longevidad", vertical_default: "longevidad", activo: true },
  { id: "camilli", nombre: "Camilli", especialidad: "Nutrición", vertical_default: "nutricion", activo: true },
  { id: "cornejo", nombre: "Cornejo", especialidad: "Kinesiología", vertical_default: "kinesiologia", activo: true },
  { id: "hiese", nombre: "Hiese", especialidad: "Kinesiología", vertical_default: "kinesiologia", activo: true },
  { id: "ottonello", nombre: "Ottonello", especialidad: "Longevidad", vertical_default: "longevidad", activo: true },
  { id: "sabate", nombre: "Sabaté", especialidad: "Sueroterapia", vertical_default: "sueroterapia", activo: true },
];

const P = (id: string) => PROFESIONALES.find((p) => p.id === id)!;

const pac = (id: string, nombre: string, vip = false): { id: string; nombre_completo: string; es_vip: boolean; primera_visita_fecha: string } => ({
  id,
  nombre_completo: nombre,
  es_vip: vip,
  primera_visita_fecha: "2025-01-01",
});

export const CITAS_SEMANA: Cita[] = [
  // LUNES 13/04
  { id: "l01", paciente: pac("c01","Fabian Carrozzino"), profesional: P("saravia"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-13T10:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "l02", paciente: pac("c02","Gerardo Bettini"), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T10:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l03", paciente: pac("c03","Federico Lepore"), profesional: P("saravia"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-13T11:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "l04", paciente: pac("c04","María Laura Fariña"), profesional: P("garbelino"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T11:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l05", paciente: pac("c05","Martin Gorosito", true), profesional: P("ayala"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-13T12:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "l06", paciente: pac("c06","Claudio G. Villar"), profesional: P("saravia"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-13T12:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "l07", paciente: pac("c07","M. Celeste Recupero"), profesional: P("ayala"), servicio: "Oligoscan · Drip · PIC", fecha_hora: "2026-04-13T12:30", duracion_min: 60, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "l08", paciente: pac("c08","Juan Manuel Gayo"), profesional: P("camilli"), servicio: "Primera consulta", fecha_hora: "2026-04-13T13:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: true },
  { id: "l09", paciente: pac("c09","Lorena Gómez Stagnaro"), profesional: P("rollan"), servicio: "Primera consulta - Longevidad", fecha_hora: "2026-04-13T13:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "l10", paciente: pac("c10","Fabio E. J. Tula"), profesional: P("saravia"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-13T13:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "l11", paciente: pac("c11","Mª Agustina Ferreira"), profesional: P("vanetta"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T13:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l12", paciente: pac("c12","Victoria Goñi Trotti", true), profesional: P("ayala"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-13T13:15", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "l13", paciente: pac("c13","Debora Seidel"), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T14:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l14", paciente: pac("c14","Ariel Edelman"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-13T14:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "l15", paciente: pac("c15","Ana Paula Ares"), profesional: P("camilli"), servicio: "Primera consulta", fecha_hora: "2026-04-13T14:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: true },
  { id: "l16", paciente: pac("c16","Gabriela Monis"), profesional: P("rollan"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T14:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l17", paciente: pac("c17","Mariano Frassia"), profesional: P("ayala"), servicio: "Primera consulta", fecha_hora: "2026-04-13T14:30", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "l18", paciente: pac("c18","Marcos A. Cardoso", true), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T15:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l19", paciente: pac("c19","S. Gonzalez Bianchi"), profesional: P("ayala"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T15:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l20", paciente: pac("c20","Martina Frittayon G.", true), profesional: P("camilli"), servicio: "Primera consulta", fecha_hora: "2026-04-13T15:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: true },
  { id: "l21", paciente: pac("c21","Florencia Safdie"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-13T15:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "l22", paciente: pac("c22","Ana Clara Porzio", true), profesional: P("ayala"), servicio: "Sobreturno", fecha_hora: "2026-04-13T15:30", duracion_min: 20, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "l23", paciente: pac("c23","Guido Giana"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-13T16:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "l24", paciente: pac("c24","Alejandro Saravia T."), profesional: P("camilli"), servicio: "Primera consulta", fecha_hora: "2026-04-13T16:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: true },
  { id: "l25", paciente: pac("c25","Lucia Pasquet"), profesional: P("garbelino"), servicio: "Primera consulta - Longevidad", fecha_hora: "2026-04-13T16:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "l26", paciente: pac("c26","Lara Rollan"), profesional: P("camilli"), servicio: "Primera consulta", fecha_hora: "2026-04-13T16:30", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: true },
  { id: "l27", paciente: pac("c27","Alma Chapero Scotta"), profesional: P("garbelino"), servicio: "PIC", fecha_hora: "2026-04-13T17:00", duracion_min: 30, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "l28", paciente: pac("c28","Alejandro Ariete"), profesional: P("saravia"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-13T17:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "l29", paciente: pac("c29","Valentina Quiñonez"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-13T18:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },

  // MARTES 14/04
  { id: "m01", paciente: pac("c30","Guillermo Galli"), profesional: P("vanetta"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T09:45", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m02", paciente: pac("c31","Raquel Mariño"), profesional: P("vanetta"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-14T10:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "m03", paciente: pac("c20","Martina Frittayon G.", true), profesional: P("camilli"), servicio: "Primera consulta online", fecha_hora: "2026-04-14T10:45", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: false },
  { id: "m04", paciente: pac("c32","Francisco Caubet"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-14T11:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "m05", paciente: pac("c33","Guillermo Sigales"), profesional: P("vanetta"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T11:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m06", paciente: pac("c34","Nicolas Tarela"), profesional: P("vanetta"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T11:15", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m07", paciente: pac("c35","Julieta Cajida"), profesional: P("rollan"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T12:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m08", paciente: pac("c36","Benjamin Lamas"), profesional: P("garbelino"), servicio: "Estudios diagnósticos", fecha_hora: "2026-04-14T12:00", duracion_min: 30, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "m09", paciente: pac("c37","Solange Amigó"), profesional: P("vanetta"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-14T12:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "m10", paciente: pac("c38","Geraldine Kohan"), profesional: P("ayala"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T12:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m11", paciente: pac("c39","Martin Quiñonez"), profesional: P("rollan"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T12:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m12", paciente: pac("c40","Romina Pigretti"), profesional: P("rollan"), servicio: "Primera consulta", fecha_hora: "2026-04-14T13:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "m13", paciente: pac("c41","Paula Cantarelli"), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T13:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m14", paciente: pac("c42","Osvaldo González", true), profesional: P("ficcadenti"), servicio: "Seguimiento · Oligoscan · d-ROMs", fecha_hora: "2026-04-14T14:00", duracion_min: 90, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "m15", paciente: pac("c39","Martin Quiñonez"), profesional: P("cornejo"), servicio: "Sesión de Kinesiología", fecha_hora: "2026-04-14T14:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "m16", paciente: pac("c43","S. Bobadilla"), profesional: P("rollan"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-14T14:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "m17", paciente: pac("c44","Paola Busnelli"), profesional: P("vanetta"), servicio: "Primera consulta", fecha_hora: "2026-04-14T14:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "m18", paciente: pac("c45","Octavio Bernardez", true), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T14:45", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m19", paciente: pac("c46","Victoria Merentiel"), profesional: P("ficcadenti"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-14T15:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "m20", paciente: pac("c47","Florencia Tesouro"), profesional: P("ayala"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-14T15:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "m21", paciente: pac("c22","Ana Clara Porzio", true), profesional: P("cornejo"), servicio: "Primera sesión - Kinesio", fecha_hora: "2026-04-14T15:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "m22", paciente: pac("c41","Paula Cantarelli"), profesional: P("garbelino"), servicio: "Sesión estética", fecha_hora: "2026-04-14T15:00", duracion_min: 45, estado: "asistio", vertical: "estetica", es_primera_vez: false },
  { id: "m23", paciente: pac("c22","Ana Clara Porzio", true), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-14T16:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "m24", paciente: pac("c45","Octavio Bernardez", true), profesional: P("cornejo"), servicio: "Sesión de seguimiento Kinesio", fecha_hora: "2026-04-14T16:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "m25", paciente: pac("c48","Rafael Nazar A."), profesional: P("ficcadenti"), servicio: "Primera consulta", fecha_hora: "2026-04-14T16:15", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "m26", paciente: pac("c49","Desirée Marmouget"), profesional: P("ottonello"), servicio: "Estudios diagnósticos", fecha_hora: "2026-04-14T17:00", duracion_min: 30, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "m27", paciente: pac("c50","Graciarena Martin"), profesional: P("cornejo"), servicio: "Sesión de Kinesiología", fecha_hora: "2026-04-14T17:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },

  // MIERCOLES 15/04
  { id: "x01", paciente: pac("c51","Sebastian Ruiz"), profesional: P("saravia"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-15T10:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "x02", paciente: pac("c52","Liliana Salgueiro"), profesional: P("saravia"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-15T11:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "x03", paciente: pac("c53","Carola Benso"), profesional: P("saravia"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T11:15", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x04", paciente: pac("c54","Paula Giacchino"), profesional: P("saravia"), servicio: "PIC", fecha_hora: "2026-04-15T11:50", duracion_min: 30, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "x05", paciente: pac("c55","Pablo Latuf"), profesional: P("saravia"), servicio: "PIC", fecha_hora: "2026-04-15T12:00", duracion_min: 30, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "x06", paciente: pac("c56","Mª Victoria Rodriguez"), profesional: P("saravia"), servicio: "Consulta seguimiento online", fecha_hora: "2026-04-15T12:10", duracion_min: 20, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x07", paciente: pac("c57","Micaela Dubra"), profesional: P("ayala"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-15T13:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "x08", paciente: pac("c58","Verónica G. Ramírez"), profesional: P("saravia"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-15T13:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "x09", paciente: pac("c59","Juan Pedro Fenner"), profesional: P("ayala"), servicio: "Proloterapia · Sueroterapia", fecha_hora: "2026-04-15T13:30", duracion_min: 60, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x10", paciente: pac("c60","Florencia Regis"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T14:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x11", paciente: pac("c61","Sebastián D'elía", true), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T14:30", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x12", paciente: pac("c62","Sebastián Palazzo"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T15:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x13", paciente: pac("c25","Lucia Pasquet"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T15:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "x14", paciente: pac("c63","Silvina Tempestini"), profesional: P("vanetta"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-15T15:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "x15", paciente: pac("c64","Liliana Rauch"), profesional: P("ayala"), servicio: "Primera consulta - Dolor", fecha_hora: "2026-04-15T15:30", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "x16", paciente: pac("c60","Florencia Regis"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T16:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "x17", paciente: pac("c65","Justo Amuchastegui"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T16:30", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "x18", paciente: pac("c66","Anahi Taborda"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-15T17:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "x19", paciente: pac("c67","Julieta Bacalov"), profesional: P("garbelino"), servicio: "Sesión estética", fecha_hora: "2026-04-15T18:00", duracion_min: 45, estado: "asistio", vertical: "estetica", es_primera_vez: false },
  { id: "x20", paciente: pac("c68","Delfina Ferro Mendez"), profesional: P("garbelino"), servicio: "Primera consulta", fecha_hora: "2026-04-15T19:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },

  // JUEVES 16/04
  { id: "j01", paciente: pac("c69","Antonella Mascioli"), profesional: P("rollan"), servicio: "Estudios · Sueroterapia", fecha_hora: "2026-04-16T09:30", duracion_min: 60, estado: "asistio", vertical: "estudios", es_primera_vez: false },
  { id: "j02", paciente: pac("c12","Victoria Goñi Trotti", true), profesional: P("hiese"), servicio: "Primera sesión - Kinesio", fecha_hora: "2026-04-16T10:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "j03", paciente: pac("c70","Lucas Fernández A."), profesional: P("hiese"), servicio: "Sesión de Kinesiología", fecha_hora: "2026-04-16T11:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "j04", paciente: pac("c71","Sofia Blacker"), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-16T14:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "j05", paciente: pac("c72","Anton Garcia"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-16T14:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "j06", paciente: pac("c73","Cecilia Bernasconi"), profesional: P("cornejo"), servicio: "Sesión de Kinesiología", fecha_hora: "2026-04-16T14:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "j07", paciente: pac("c74","Eduardo D. Monteros"), profesional: P("saravia"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-16T14:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "j08", paciente: pac("c19","S. Gonzalez Bianchi"), profesional: P("ayala"), servicio: "Consulta · Sueroterapia", fecha_hora: "2026-04-16T14:30", duracion_min: 60, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "j09", paciente: pac("c75","S. E. Fernandez"), profesional: P("saravia"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-16T14:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "j10", paciente: pac("c76","Andrea Sassi"), profesional: P("ayala"), servicio: "Primera consulta", fecha_hora: "2026-04-16T15:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "j11", paciente: pac("c77","Marianela Percario"), profesional: P("cornejo"), servicio: "Sesión de Kinesiología", fecha_hora: "2026-04-16T15:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "j12", paciente: pac("c78","Raul R. Ramirez"), profesional: P("saravia"), servicio: "Primera consulta", fecha_hora: "2026-04-16T15:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "j13", paciente: pac("c79","Laura Sanchez"), profesional: P("saravia"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-16T15:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "j14", paciente: pac("c77","Marianela Percario"), profesional: P("ficcadenti"), servicio: "Sueroterapia · Estudios", fecha_hora: "2026-04-16T16:00", duracion_min: 60, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "j15", paciente: pac("c80","Mirna J. Lopez"), profesional: P("ayala"), servicio: "Primera consulta", fecha_hora: "2026-04-16T16:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "j16", paciente: pac("c81","Nicolás Ardanaz"), profesional: P("saravia"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-16T16:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "j17", paciente: pac("c82","Nicolás P. Minafaro"), profesional: P("saravia"), servicio: "Primera consulta", fecha_hora: "2026-04-16T16:15", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: true },
  { id: "j18", paciente: pac("c81","Nicolás Ardanaz"), profesional: P("cornejo"), servicio: "Sesión de Kinesiología", fecha_hora: "2026-04-16T17:00", duracion_min: 45, estado: "asistio", vertical: "kinesiologia", es_primera_vez: false },
  { id: "j19", paciente: pac("c39","Martin Quiñonez"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-16T18:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },

  // VIERNES 17/04
  { id: "v01", paciente: pac("c83","Anibal Ramos"), profesional: P("vanetta"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-17T09:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "v02", paciente: pac("c84","Lucia Agundez"), profesional: P("vanetta"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T10:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "v03", paciente: pac("c85","Maria Lorena Cavero"), profesional: P("camilli"), servicio: "Primera consulta", fecha_hora: "2026-04-17T11:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: true },
  { id: "v04", paciente: pac("c86","Carola Chasco Wagner"), profesional: P("vanetta"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T11:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "v05", paciente: pac("c87","Guillermo Dotta"), profesional: P("saravia"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T11:30", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "v06", paciente: pac("c88","Dahian Rocchini", true), profesional: P("ficcadenti"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-17T12:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "v07", paciente: pac("c07","M. Celeste Recupero"), profesional: P("camilli"), servicio: "Nutrición - seguimiento", fecha_hora: "2026-04-17T12:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: false },
  { id: "v08", paciente: pac("c88","Dahian Rocchini", true), profesional: P("vanetta"), servicio: "PRP Hiperconcentrado", fecha_hora: "2026-04-17T12:00", duracion_min: 60, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "v09", paciente: pac("c85","Maria Lorena Cavero"), profesional: P("saravia"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T12:30", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "v10", paciente: pac("c89","Natalia Irene Ramos"), profesional: P("camilli"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T13:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: false },
  { id: "v11", paciente: pac("c85","Maria Lorena Cavero"), profesional: P("rollan"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-17T13:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "v12", paciente: pac("c90","Aldana Rocchini"), profesional: P("vanetta"), servicio: "Suero · Longevidad · Estética", fecha_hora: "2026-04-17T13:00", duracion_min: 90, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "v13", paciente: pac("c90","Aldana Rocchini"), profesional: P("camilli"), servicio: "Nutrición - seguimiento", fecha_hora: "2026-04-17T14:00", duracion_min: 30, estado: "asistio", vertical: "nutricion", es_primera_vez: false },
  { id: "v14", paciente: pac("c91","Raul E. Michel"), profesional: P("rollan"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-17T14:30", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "v15", paciente: pac("c92","Daniela Guardia"), profesional: P("garbelino"), servicio: "Sesión estética", fecha_hora: "2026-04-17T15:00", duracion_min: 45, estado: "asistio", vertical: "estetica", es_primera_vez: false },
  { id: "v16", paciente: pac("c93","Carlos D. Hawsa"), profesional: P("ottonello"), servicio: "Primera consulta", fecha_hora: "2026-04-17T16:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "v17", paciente: pac("c25","Lucia Pasquet"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T16:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "v18", paciente: pac("c94","Virginia Oggero"), profesional: P("ayala"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T17:00", duracion_min: 30, estado: "asistio", vertical: "dolor", es_primera_vez: false },
  { id: "v19", paciente: pac("c95","Martina Damilano"), profesional: P("garbelino"), servicio: "Primera consulta", fecha_hora: "2026-04-17T17:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
  { id: "v20", paciente: pac("c96","Cecilia A. M. Illa"), profesional: P("sabate"), servicio: "Sesión de Sueroterapia", fecha_hora: "2026-04-17T17:00", duracion_min: 45, estado: "asistio", vertical: "sueroterapia", es_primera_vez: false },
  { id: "v21", paciente: pac("c97","Nicolas Grunding"), profesional: P("garbelino"), servicio: "Consulta de seguimiento", fecha_hora: "2026-04-17T18:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: false },
  { id: "v22", paciente: pac("c98","Mariana Paula Vidal"), profesional: P("ottonello"), servicio: "Primera consulta", fecha_hora: "2026-04-17T19:00", duracion_min: 30, estado: "asistio", vertical: "longevidad", es_primera_vez: true },
];

export const KPI_SEMANA: KpiSemana = {
  visitas_unicas: 118,
  tasa_asistencia: 88.3,
  primera_vez: 23,
  vip: 9,
  canceladas: 17,
  no_shows: 0,
  tasa_pv: 19.5,
  vs_semana_anterior: {
    visitas_unicas: 128,
    tasa_asistencia: 88.7,
    primera_vez: 21,
    vip: 8,
    canceladas: 13,
  },
};

export const DISTRIBUCION_VERTICALES: DistribucionVertical[] = [
  { vertical: "sueroterapia", cantidad: 35, porcentaje: 27.3 },
  { vertical: "dolor", cantidad: 33, porcentaje: 25.8 },
  { vertical: "longevidad", cantidad: 26, porcentaje: 20.3 },
  { vertical: "estudios", cantidad: 11, porcentaje: 8.6 },
  { vertical: "nutricion", cantidad: 10, porcentaje: 7.8 },
  { vertical: "kinesiologia", cantidad: 9, porcentaje: 7.0 },
  { vertical: "estetica", cantidad: 4, porcentaje: 3.1 },
];

export const TURNOS_POR_DIA: TurnosDia[] = [
  { dia: "Lun", fecha: "13/04", cantidad: 29 },
  { dia: "Mar", fecha: "14/04", cantidad: 27 },
  { dia: "Mié", fecha: "15/04", cantidad: 20 },
  { dia: "Jue", fecha: "16/04", cantidad: 19 },
  { dia: "Vie", fecha: "17/04", cantidad: 22 },
];

export const PERFORMANCE_PROFESIONALES: PerformanceProfesional[] = [
  { profesional: P("ayala"), turnos: 22, asistidos: 20, cancelados: 1, no_shows: 1, primera_vez: 7, vip: 2, tasa_asistencia: 91.0, tasa_ocupacion: 84.0 },
  { profesional: P("saravia"), turnos: 19, asistidos: 17, cancelados: 2, no_shows: 0, primera_vez: 6, vip: 0, tasa_asistencia: 89.5, tasa_ocupacion: 78.0 },
  { profesional: P("garbelino"), turnos: 16, asistidos: 15, cancelados: 1, no_shows: 0, primera_vez: 4, vip: 0, tasa_asistencia: 93.8, tasa_ocupacion: 72.0 },
  { profesional: P("ficcadenti"), turnos: 12, asistidos: 12, cancelados: 0, no_shows: 0, primera_vez: 1, vip: 3, tasa_asistencia: 100.0, tasa_ocupacion: 95.0 },
  { profesional: P("rollan"), turnos: 10, asistidos: 9, cancelados: 1, no_shows: 0, primera_vez: 2, vip: 0, tasa_asistencia: 90.0, tasa_ocupacion: 68.0 },
  { profesional: P("vanetta"), turnos: 13, asistidos: 12, cancelados: 1, no_shows: 0, primera_vez: 1, vip: 1, tasa_asistencia: 92.3, tasa_ocupacion: 81.0 },
  { profesional: P("camilli"), turnos: 11, asistidos: 10, cancelados: 1, no_shows: 0, primera_vez: 3, vip: 1, tasa_asistencia: 90.9, tasa_ocupacion: 76.0 },
  { profesional: P("cornejo"), turnos: 8, asistidos: 7, cancelados: 1, no_shows: 0, primera_vez: 0, vip: 2, tasa_asistencia: 87.5, tasa_ocupacion: 65.0 },
  { profesional: P("hiese"), turnos: 3, asistidos: 3, cancelados: 0, no_shows: 0, primera_vez: 0, vip: 1, tasa_asistencia: 100.0, tasa_ocupacion: 60.0 },
  { profesional: P("ottonello"), turnos: 3, asistidos: 3, cancelados: 0, no_shows: 0, primera_vez: 2, vip: 0, tasa_asistencia: 100.0, tasa_ocupacion: 55.0 },
  { profesional: P("sabate"), turnos: 1, asistidos: 1, cancelados: 0, no_shows: 0, primera_vez: 0, vip: 0, tasa_asistencia: 100.0, tasa_ocupacion: 40.0 },
];

export const EMBUDOS_HORARIOS: EmbudioHorario[] = [
  { hora: "09:00", lunes: 0, martes: 0, miercoles: 0, jueves: 0, viernes: 0, total: 0 },
  { hora: "09:30", lunes: 0, martes: 1, miercoles: 0, jueves: 1, viernes: 2, total: 4 },
  { hora: "10:00", lunes: 1, martes: 1, miercoles: 1, jueves: 1, viernes: 2, total: 6 },
  { hora: "10:30", lunes: 1, martes: 0, miercoles: 0, jueves: 0, viernes: 0, total: 1 },
  { hora: "11:00", lunes: 1, martes: 2, miercoles: 2, jueves: 1, viernes: 2, total: 8 },
  { hora: "11:30", lunes: 1, martes: 0, miercoles: 0, jueves: 0, viernes: 1, total: 2 },
  { hora: "12:00", lunes: 2, martes: 3, miercoles: 2, jueves: 0, viernes: 3, total: 10 },
  { hora: "12:30", lunes: 1, martes: 2, miercoles: 1, jueves: 0, viernes: 1, total: 5 },
  { hora: "13:00", lunes: 4, martes: 2, miercoles: 2, jueves: 0, viernes: 3, total: 11 },
  { hora: "13:30", lunes: 0, martes: 1, miercoles: 1, jueves: 0, viernes: 1, total: 3 },
  { hora: "14:00", lunes: 4, martes: 4, miercoles: 2, jueves: 4, viernes: 2, total: 16 },
  { hora: "14:30", lunes: 1, martes: 1, miercoles: 1, jueves: 2, viernes: 1, total: 6 },
  { hora: "15:00", lunes: 5, martes: 4, miercoles: 3, jueves: 3, viernes: 1, total: 16 },
  { hora: "15:30", lunes: 1, martes: 0, miercoles: 1, jueves: 1, viernes: 0, total: 3 },
  { hora: "16:00", lunes: 3, martes: 3, miercoles: 2, jueves: 3, viernes: 2, total: 13 },
  { hora: "16:30", lunes: 1, martes: 0, miercoles: 1, jueves: 1, viernes: 0, total: 3 },
  { hora: "17:00", lunes: 1, martes: 2, miercoles: 1, jueves: 1, viernes: 3, total: 8 },
  { hora: "17:30", lunes: 1, martes: 0, miercoles: 0, jueves: 0, viernes: 0, total: 1 },
  { hora: "18:00", lunes: 1, martes: 0, miercoles: 1, jueves: 1, viernes: 1, total: 4 },
  { hora: "19:00", lunes: 0, martes: 0, miercoles: 1, jueves: 0, viernes: 1, total: 2 },
];
